services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
  spring-docker:
    container_name: spring-server
    image: alcohol-friday:0.0.1
    restart: always
    ports:
      - 8080:8080